version: '3.9'

services:
    sqlite3:
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - ./database/sqlite3/data:/database/sqlite3/data

    migrate:
        image: migrate/migrate
        restart: on-failure
        volumes:
            - ./database/sqlite3/migrations:/database/sqlite3/migrations

        command:
            [
                "-path",
                "database/sqlite3/migrations",
                "-database",
                "sqlite3:/./cmd/db.sqlite/goreact?sslmode=disable",
                "up"
            ]
        links:
            - sqlite3
        depends_on:
            - sqlite3

    auth:
        build:
            context: ./api
        ports:
            - 1111:8080
        depends_on:
            - sqlite3
        env_file:
            - .env
        environment:
            - SERVER_HOST=0.0.0.0
            - ENV=prod
        tty: true
        restart: on-failure
        volumes:
            - ./api/logs:/api/logs
        networks:
            - new

networks:
    new:
        driver: bridge
